"""Create toilets table

Revision ID: beee93e9b43b
Revises: 
Create Date: 2024-10-19 09:41:22.201541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beee93e9b43b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toilets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('water_fountain', sa.Boolean(), nullable=True),
    sa.Column('bottle_filler', sa.Boolean(), nullable=True),
    sa.Column('jug_filler', sa.Boolean(), nullable=True),
    sa.Column('dog_fountain', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('access', sa.String(length=50), nullable=True),
    sa.Column('public_access_hours_open', sa.Time(), nullable=True),
    sa.Column('public_access_hours_close', sa.Time(), nullable=True),
    sa.Column('public_access_days', sa.String(length=50), nullable=True),
    sa.Column('data_as_of', sa.DateTime(), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toilets')
    # ### end Alembic commands ###
